WORDS = [
    "10 Guy",
    "A fine addition to my collection",
    "Actual Advice Mallard",
    "All the Things",
    "Ancient Aliens",
    "Ancient Aliens",
    "And It’s Gone",
    "Annoyed Picard",
    "Awkward Moment Seal",
    "Baby Godfather",
    "Bad Joke Eel",
    "Bad Luck Brian",
    "Batman Slapping Robin",
    "Bear Grylls",
    "Black Girl Wat",
    "Blackjack and Hookers",
    "Blank Nut Button",
    "Boardroom Meeting Suggestion",
    "Brace Yourselves X is Coming",
    "Business Cat",
    "But Thats None Of My Business",
    "Captain Hindsight",
    "Car Salesman",
    "Change my mind",
    "College Freshman",
    "College Liberal",
    "Confessions Bear",
    "Conspiracy Keanu",
    "Courage Wolf",
    "Creepy Condescending Wonka",
    "Crying Michael Jordan",
    "Dabbing Squidward",
    "Dat Boi",
    "Disaster Girl",
    "Distracted Boyfriend",
    "Double Rainbow (Across the sky)",
    "Downvoting Roman",
    "Drake Likes/Dislikes",
    "Drunk Baby",
    "E (Lord Farquad)",
    "Elon Smoking",
    "Eric Andre shooting",
    "Ermahgerd",
    "Everyone Loses Their Mind",
    "Evil Kermit",
    "Evil Plotting Racoon",
    "Excuse me, WTF? Fallout",
    "Expanding Brain",
    "Facepalm",
    "First Day on the Internet Kid",
    "First World Problems",
    "Forever Alone",
    "Foul Bachelor Frog",
    "Free Real Estate",
    "Futurama Squinting Fry",
    "Good Guy Greg",
    "Grandma Finds the Internet",
    "Grinds My Gears",
    "Grumpy Cat",
    "Had to do it to 'em",
    "Harambe (rip)",
    "Hard Pills to Swallow",
    "Hide the Pain Harold",
    "High Expectations Asian Father",
    "Hipster Barista",
    "Hipster Kitten",
    "I Guarantee It",
    "I prefer the real ____. Perfection",
    "Inhaling Seagull",
    "Insanity Wolf",
    "Internet Husband",
    "Is That A Chicken (Kylie Jenner)",
    "Is This A Pigeon",
    "It Was a Good Day",
    "It's wednesday my dudes",
    "I’ll Have You Know",
    "Just like the simulations",
    "Keyboard Cat",
    "Kowalski analysis",
    "Lazy College Senior",
    "Left Exit 12 Off Ramp",
    "Leonardo Dicaprio Cheers",
    "Lisa giving a presentation",
    "Look at this photograph",
    "Mario vs Luigi",
    "Master's Blessing (man giving sword)",
    "Matrix Morpheus",
    "Maury Lie Detector",
    "Mocking Spongebob",
    "Most Interesting Man in the World",
    "moth LAMP",
    "Neil deGrasse Tyson",
    "Nek",
    "None of My Business",
    "Nyan Cat",
    "One Does Not Simply",
    "Oprah You Get A",
    "Overly Manly Man",
    "Paranoid Parrot",
    "Pedo Bear",
    "Pepe the frog (rare)",
    "Pepperidge Farm Remembers",
    "Philosoraptor",
    "A Potato Flew Around My Room",
    "Push It Somewhere Else Patrick",
    "Pyramid of Intelect",
    "Rafiki The Wise",
    "Ralph Nelson \"I'm in danger\"",
    "Roll Safe Think About It",
    "Runescape Gnome Child",
    "Salt Bae",
    "Satisfied Seal",
    "Schrute Facts",
    "Scumbag Brain",
    "Scumbag Steve",
    "Scumbag Teacher",
    "Skeptical 3rd World Kid",
    "Slowpoke",
    "Snapchat Hotdog",
    "So I Got That Goin’ For Me, Which is Nice",
    "Socially Awkward Penguin",
    "Sophisticated Cat",
    "Spider-Man Masterbating",
    "Stoner Dog",
    "Strong arms holding (Epic Handshake / Venn Diagram)",
    "Success Kid",
    "Sudden Clarity Clarence",
    "Super Cool Ski Instructor",
    "Surprised Pikachu",
    "Swords of the round table",
    "T Posing",
    "That wasn't very cash money of you",
    "The Most Interesting Man In The World",
    "The Rock Driving",
    "They did surgery on a grape",
    "Third World Success",
    "Thomas the tank engine",
    "Tide Pods",
    "Too Damn High",
    "Trump Bill Signing",
    "Two Buttons",
    "Ugandan Knuckles",
    "Unpopular Opinion Puffin",
    "Upvoting Obama",
    "Waiting Skeleton",
    "Is that a weed? I'm calling 911 (crayon)",
    "Whoever Threw that...",
    "X All The Y",
    "Y U No",
    "Yao Ming",
    "Yo Dawg",
    "Yodel Kid",
    "You Can’t Explain That",
    "You won this hole",
    "Y’all Got Anymore of...",
]

NORMAL_WORDS = [
    "acorn",
    "airplane",
    "alarm clock",
    "alcohol",
    "alien",
    "alligator",
    "america",
    "anchor",
    "angel",
    "ankle",
    "ant",
    "ants",
    "anvil",
    "apple",
    "arcade machine",
    "archer",
    "arm",
    "armor",
    "astronaut",
    "australia",
    "autumn",
    "axe",
    "baby",
    "bacon",
    "bag",
    "bagel",
    "baggage",
    "balloon",
    "balloons",
    "bamboo",
    "banana",
    "bank",
    "barbie",
    "barn",
    "base",
    "baseball",
    "basketball",
    "basketball court",
    "bat",
    "bathroom",
    "batman",
    "battery",
    "battleship",
    "beach",
    "beans",
    "bear",
    "beard",
    "beaver",
    "bed",
    "beehive",
    "beer",
    "bell",
    "bells",
    "belly button",
    "bench",
    "berry",
    "bicycle",
    "bike",
    "bikini",
    "binoculars",
    "bird",
    "birthday cake",
    "blanket",
    "blocks",
    "boar",
    "boat",
    "bomb",
    "bone",
    "booger",
    "book",
    "bookcase",
    "bookstore",
    "boots",
    "booty",
    "bottle",
    "bow",
    "bowl",
    "bowtie",
    "box",
    "boy",
    "bracelet",
    "brain",
    "branch",
    "bread",
    "bridge",
    "broomstick",
    "brush",
    "bubble",
    "bucket",
    "bug",
    "building",
    "bumblebee",
    "bunny",
    "burger",
    "burn",
    "bus",
    "butterfly",
    "button",
    "cabin",
    "cactus",
    "cage",
    "cake",
    "calculator",
    "camel",
    "camera",
    "camp fire",
    "campfire",
    "canada",
    "candle",
    "candy",
    "candy cane",
    "cannibal",
    "cap",
    "cape",
    "capture",
    "car",
    "card",
    "carrot",
    "castle",
    "cat",
    "cauldron",
    "cave",
    "cd",
    "cereal",
    "chair",
    "chalk",
    "chard",
    "charmander",
    "cheek",
    "cheese",
    "cheeseburger",
    "chef",
    "cherry",
    "chess",
    "chest",
    "chestnut",
    "chestplate",
    "chicken",
    "children",
    "chimney",
    "chin",
    "chocolate",
    "christmas",
    "christmas tree",
    "cigar",
    "cinema",
    "circle",
    "circus",
    "clock",
    "cloud",
    "clown",
    "coal",
    "coat",
    "coconut",
    "coffee",
    "cold",
    "comet",
    "compass",
    "computer",
    "cone",
    "confused",
    "cookie",
    "cookies",
    "cork",
    "corn",
    "cort",
    "couch",
    "cow",
    "crab",
    "crack",
    "crayon",
    "creeper",
    "crib",
    "crowd",
    "crown",
    "crying",
    "cup",
    "cupcake",
    "cyclop",
    "cyclops",
    "dance",
    "darts",
    "decorations",
    "desert",
    "desk",
    "diamond",
    "diamonds",
    "diary",
    "dice",
    "dinosaur",
    "disco",
    "dog",
    "doll",
    "dolphin",
    "domino",
    "dominoes",
    "donut",
    "door",
    "door knob",
    "doormat",
    "dragon",
    "draw my thing",
    "dream",
    "dress",
    "drill",
    "drink",
    "drool",
    "drum",
    "drums",
    "duck",
    "eagle",
    "ear",
    "ears",
    "earth",
    "egg",
    "eggnog",
    "eggs",
    "elbow",
    "electricity",
    "elephant",
    "elevator",
    "elf",
    "emerald",
    "emeralds",
    "ender dragon",
    "eraser",
    "erupt",
    "explosion",
    "eye",
    "eyepatch",
    "eyes",
    "face",
    "facebook",
    "fall",
    "family",
    "farm",
    "fat",
    "father",
    "fighting",
    "filing",
    "finger",
    "fire",
    "fireplace",
    "fishing",
    "fishing pole",
    "fishing rod",
    "fist",
    "flag",
    "flamingo",
    "flashlight",
    "flint",
    "flower",
    "flowers",
    "flute",
    "fly",
    "food",
    "football",
    "forest",
    "fountain",
    "frenchfries",
    "fridge",
    "fries",
    "frisbee",
    "frog",
    "frozen",
    "galaxy",
    "gapples",
    "garbage",
    "garden",
    "gate",
    "ghast",
    "ghost",
    "giant",
    "gift",
    "gingerbread",
    "gingerbread man",
    "giraffe",
    "girl",
    "glacier",
    "glasses",
    "godzilla",
    "gold",
    "goldfish",
    "golem",
    "golf club",
    "grapes",
    "grass",
    "grave",
    "gravestone",
    "graveyard",
    "grim reaper",
    "grinch",
    "grocer",
    "guard",
    "guitar",
    "gun",
    "hair",
    "hair dryer",
    "halloween",
    "hammer",
    "hamster",
    "hand",
    "handcuffs",
    "hang",
    "harry potter",
    "hat",
    "head",
    "headphones",
    "heart",
    "hedgehog",
    "helicopter",
    "helmet",
    "hill",
    "hippo",
    "hobo",
    "hockey",
    "holding hands",
    "hook",
    "hopscotch",
    "horse",
    "horse riding",
    "hospital",
    "hot air balloon",
    "hot chocolate",
    "hotdog",
    "house",
    "hula hoop",
    "ice",
    "ice cream",
    "ice hockey",
    "ice skating",
    "iceberg",
    "icecream",
    "icicle",
    "igloo",
    "ipod",
    "iron ore",
    "jacket",
    "jam",
    "james bond",
    "jar",
    "jellyfish",
    "jingle bells",
    "joker",
    "juggle",
    "jump",
    "jungle kitten",
    "kangaroo",
    "key",
    "keyboard",
    "king",
    "kirby",
    "kiss",
    "kitchen",
    "kite",
    "kitten",
    "knot",
    "ladybug",
    "lake",
    "lamp",
    "lance",
    "laptop",
    "lava",
    "lawnmower",
    "leaf",
    "leash",
    "letter",
    "letterbox",
    "light",
    "lightbulb",
    "lighthouse",
    "lightning",
    "lightsaber",
    "lion",
    "lipstick",
    "lizard",
    "llama",
    "lobster",
    "lollipop",
    "love",
    "luigi",
    "magic",
    "magnet",
    "mail",
    "mailman",
    "mansion",
    "mario",
    "math",
    "mattress",
    "melon",
    "microsoft",
    "milk",
    "minecart",
    "minecraft",
    "mineplex",
    "miner",
    "mistletoe",
    "mittens",
    "money",
    "monitor",
    "monkey",
    "moon",
    "moose",
    "mosquito",
    "mother",
    "motorbike",
    "motorcycle",
    "mountain",
    "mountain bike",
    "mouse",
    "mouth",
    "movie",
    "mudkip",
    "muffin",
    "muscles",
    "mushroom",
    "music",
    "nail",
    "neck",
    "necklace",
    "nether",
    "nether portal",
    "newspaper",
    "night",
    "night time",
    "nightmare",
    "ninja",
    "nintendo",
    "noodles",
    "north pole",
    "nose",
    "notebook",
    "nutcracker",
    "obsidian",
    "ocean",
    "octagon",
    "orange",
    "ornament",
    "owl",
    "paint",
    "painting",
    "pajamas",
    "palace",
    "pancake",
    "panda",
    "pants",
    "paper",
    "park",
    "party",
    "peach",
    "peanut",
    "peasant",
    "pen",
    "pencil",
    "penguin",
    "pepsi",
    "person",
    "phone",
    "photo",
    "photograph",
    "piano",
    "pickle",
    "picnic",
    "pie",
    "pig",
    "pikachu",
    "pillow",
    "pineapple",
    "pinecone",
    "ping pong",
    "pinwheel",
    "pirate",
    "pistol",
    "piston",
    "pizza",
    "plane",
    "planet",
    "plant",
    "plate",
    "playstation",
    "plumber",
    "pokeball",
    "pokemon",
    "police",
    "pool",
    "pool party",
    "poop",
    "popcorn",
    "popsicle",
    "portal",
    "pot of gold",
    "potato",
    "pregnant",
    "present",
    "presenter",
    "pretzel",
    "prince",
    "princess",
    "prison",
    "prize",
    "pull",
    "pumpkin",
    "pumpkin pie",
    "punch",
    "puncture",
    "puppet",
    "puppy",
    "purse",
    "push",
    "pyramid",
    "queen",
    "quick",
    "rabbit",
    "racecar",
    "radar",
    "radio",
    "rain",
    "rainbow",
    "raspberry",
    "redstone",
    "refrigerator",
    "reindeer",
    "remote",
    "restaurant",
    "rhinoceros",
    "rice",
    "rifle",
    "ring",
    "river",
    "road",
    "robot",
    "rocket",
    "rocking chair",
    "roll",
    "roof",
    "rope",
    "rose",
    "round",
    "royal",
    "rubbish",
    "rug",
    "ruins",
    "ruler",
    "saddle",
    "sailboat",
    "salad",
    "salsa",
    "salt and pepper",
    "sandwich",
    "santa",
    "santa hat",
    "scale",
    "scarf",
    "school",
    "scissors",
    "screw",
    "scrooge",
    "sea",
    "seahorse",
    "seashell",
    "seesaw",
    "shark",
    "sheep",
    "shell",
    "shield",
    "shirt",
    "shoe",
    "shopping cart",
    "shorts",
    "shotgun",
    "shout",
    "shovel",
    "sideburns",
    "sidewalk",
    "skate",
    "skateboard",
    "skeleton",
    "ski",
    "skiing",
    "skinny",
    "skirt",
    "skull",
    "skunk",
    "skype",
    "sled",
    "sleeping",
    "sleigh",
    "slide",
    "slime",
    "slippers",
    "sloth",
    "smile",
    "snail",
    "snake",
    "snorlax",
    "snow fight",
    "snow fort",
    "snowball",
    "snowball fight",
    "snowboard",
    "snowflake",
    "snowman",
    "soap",
    "sock",
    "socks",
    "soda",
    "song",
    "soup",
    "spaceship",
    "spaghetti",
    "speaker",
    "speedboat",
    "spider",
    "spider web",
    "spikes",
    "sponge",
    "spoon",
    "spray",
    "spring",
    "sprout",
    "squid",
    "squirrel",
    "stable",
    "stage",
    "stain",
    "staircase",
    "stairs",
    "stamp",
    "star",
    "stars",
    "state",
    "statue",
    "stingray",
    "stocking",
    "stomach",
    "stool",
    "stop sign",
    "stoplight",
    "storm",
    "strawberry",
    "stump",
    "sugar",
    "suitcase",
    "summer",
    "sun",
    "sunflower",
    "sunglasses",
    "sunrise",
    "sunset",
    "superman",
    "sushi",
    "sweater",
    "swimming",
    "swimming pool",
    "swing",
    "swordfish",
    "syrup",
    "table",
    "taco",
    "tail",
    "tank",
    "tape",
    "taxi",
    "teapot",
    "tears",
    "technology",
    "teddy",
    "telephone",
    "telescope",
    "television",
    "temple",
    "tennis",
    "tennis racket",
    "tent",
    "tetris",
    "thief",
    "thorn",
    "thumb",
    "tiger",
    "time",
    "tiny",
    "toast",
    "toaster",
    "toilet",
    "tomato",
    "tooth",
    "toothbrush",
    "top hat",
    "torch",
    "tornado",
    "towel",
    "tower",
    "toys",
    "traffic lights",
    "trash",
    "treasure",
    "tree",
    "treehouse",
    "trick",
    "trick or treat",
    "troll face",
    "truck",
    "trumpet",
    "turtle",
    "tv",
    "twitter",
    "umbrella",
    "unicorn",
    "united states",
    "uppercut",
    "usb",
    "vest",
    "video game",
    "violin",
    "volcano",
    "vomit",
    "wagon",
    "waist",
    "wallet",
    "washing machine",
    "watch",
    "water",
    "water gun",
    "waterfall",
    "watering can",
    "watermelon",
    "whale",
    "wheat",
    "whisk",
    "whistle",
    "wind",
    "windmill",
    "window",
    "winter",
    "witch",
    "wither",
    "wizard",
    "wolf",
    "worm",
    "wrench",
    "xbox",
    "yawn",
    "yelling",
    "yo-yo",
    "yoshi",
    "youtube",
    "zebra",
    "zipper",
    "zombie",
    "zombie pigman",
    "zoo",
]